### ISSUE TITLE
1.3-dev auto-update no longer executed

### ISSUE THREAD

**Issue by fkoester** [TuRz4m/Ark-docker#10]
I noticed that using the 1.3-dev branch the auto-update on start is not working anymore, although this setting should be the default.

That's my `docker-compose.yml`:

```
ark:
  image: turzam/ark:1.3-dev
  net: "host"
  ports:
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330
  environment:
    - SESSIONNAME=The Gold Enigmas
    - BACKUPONSTOP=1
    - SERVERPASSWORD=rexdodo
    - ADMINPASSWORD=EgAPisw
  volumes:
    - /mnt/data/docker/arkserver:/ark
```

As you can see, `UPDATEPONSTART` is not explicetely set but according to the README `UPDATEPONSTART=1` should be the default (And this worked using the master branch).

I can force an update with:

```
docker exec arkserver_ark_1 arkmanager update --force
```
